version: "3"
services:
  postgresql:
    container_name: hypeDB
    restart: unless-stopped
    env_file: .env
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - hype-data:/var/lib/postgresql/data/ 
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - "5432:5432"
    networks:
      - hype

volumes:
  hype-data:

networks:
  hype:
    name: hype
    driver: bridge